### ISSUE TITLE
Glimmer2 Support

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/ember-mobiledoc-dom-renderer#18]
Looks like Glimmer2 changes the way the dom renderer work, as [this](https://github.com/bustlelabs/ember-mobiledoc-dom-renderer/blob/3aebfacde42f575abe93e79e48111be07e63a40f/addon/components/render-mobiledoc.js#L95-L97) no longer returns anything and so it asserts:

```javascript
    let emberRenderer = this.get('renderer');
    let dom = emberRenderer && emberRenderer._dom;
    assert('Unable to get renderer dom helper', !!dom);
```

**Comment by bantic** [comment]
fix released in [v0.5.3](https://github.com/bustlelabs/ember-mobiledoc-dom-renderer/releases/tag/v0.5.3)
