### ISSUE TITLE
expose property on component to override card class names

### ISSUE THREAD

**Issue by bantic** [bustlelabs/ember-mobiledoc-dom-renderer#4]
Cards currently get placed in a wrapper div with class name of '__rendered-mobiledoc-card' and '__rendered-mobiledoc-card-${cardName}'. The `{{render-mobiledoc}}` component should expose a way for a consumer to specify the card element class name(s)

**Comment by mixonic** [comment]
I'd like the classes to stay 100% internal. They can add a DOM node and style it in their own domain, and that should be pretty easy to do.

**Comment by bantic** [comment]
+1
