### ISSUE TITLE
Inject attributes into markup tags.

### ISSUE THREAD

**Issue by camerondunford** [bustlelabs/ember-mobiledoc-dom-renderer#8]
Is it possible to add tags to markup elements?

For example, adding ```target="_blank"``` to anchor tags:

```
_linkTargetBlank(mobiledoc) {
  let markups = mobiledoc.sections[0] || [];

  // new anchor markup sections
  let newMarkups = markups.map(markup => {
    // skip everything but anchors
    if (markup[0] !== 'a') {
      return markup;
    }

    markup.pushObject(['target', '_blank']);
    return markup;
  });

  // replace markup sections
  mobiledoc.sections[0] = newMarkups;
  return mobiledoc;
},
```

**Comment by mixonic** [comment]
Customizing the rendering of markups is not supported today, though Garth and I have discussed it.

If you want to use target blank, I suggest using JavaScript to capture the clicks on links and open windows that way.

**Comment by camerondunford** [comment]
It would be a welcome feature. Thank you for your response & suggested workaround.
